rd_wr_ls/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from rest_framework_jwt.views import obtain_jwt_token

from wrlapp import views as wrlappview
from wrlapp.views import ListPostsView

urlpatterns = [
    path('', include('wrlapp.urls')),
    path('', wrlappview.show_all, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-token-auth/', obtain_jwt_token, name='create-token'),
    re_path('api/(?P<version>(v1|v2))/posts', ListPostsView.as_view(), name="posts-all"),
]

users/urls.py
from django.urls import include, path

from . import views

app_name = 'users'

urlpatterns = [
   
]

wrlapp/urls.py
from django.urls import include, path, re_path

from . import views
from .views import ListPostsView,LoginView

app_name = 'wrlapp'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.show_all, name='show'),
    path('create', views.create_post, name='create'),
    path('view/<int:id>', views.retrive_post, name='retrive'),
    path('<int:id>/update', views.update_post, name='update'),
    path('<int:id>/delete', views.delete_post, name='delete'),
    path('how_it_work', views.how_it_work, name="work"),
    path('auth/login/', LoginView.as_view(), name="auth-login"),
    path('medium/view/<int:id>', views.retriveMediumContent, name='mediumViewOneContent'),
    re_path('^medium/view',  views.showMediumContent, name="mediumViewContent"),
    re_path('^medium/', views.getMediumContent, name="mediumCreateContent"),
    # path('posts/', ListPostsView.as_view(), name="posts-all")
    # path(r'^accounts/', include('allauth.urls')),
]

users/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

# Create your models here.

class CustomUserManager(UserManager):
	pass

class CustomUser(AbstractUser):
	objects = CustomUserManager()

wrlapp/models.py
from django.conf import settings
from django.db import models


class Posts(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
							 default = 1,
							 on_delete = models.CASCADE)
	title = models.CharField(max_length = 100)
	content = models.TextField()
	read_time = models.TimeField(null = True, blank = True)
	updated = models.DateTimeField(auto_now = True, auto_now_add = False)
	create_date = models.DateTimeField(auto_now = False, auto_now_add = True)
	is_public = models.BooleanField()


	def __str__(self):
		return  self.title


class FetchUrlContent(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
							 default = 1,
							 on_delete = models.CASCADE)
	url = models.CharField(max_length = 500)
	getUrlContent = models.TextField()

	def __str__(self):
		return  self.url

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

	class Meta(UserCreationForm.Meta):
		model = CustomUser
		fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

	class Meta(UserChangeForm.Meta):
		model = CustomUser
		fields = UserChangeForm.Meta.fields

wrlapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Posts, FetchUrlContent

class PostForm(forms.ModelForm):
	class Meta:
		model = Posts
		fields = [
			'title',
			'content',
			'is_public']

class FetchUrlContentForm(forms.ModelForm):
	class Meta:
		model = FetchUrlContent
		fields = [
		'url']
		# 'getUrlContent']

users/views.py
from django.shortcuts import render

# Create your views here.

wrlapp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect

# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
# from django.contrib.auth import authenticate, login
from rest_framework_jwt.settings import api_settings
from rest_framework import permissions

from allauth.account.views import SignupView, LoginView
from rest_framework import generics
from .forms import PostForm, FetchUrlContentForm
from .models import Posts, FetchUrlContent
from .serializers import PostsSerializer

# external assets here
from assets.customUtill import mediumContent

from requests import get

 
# JWT settings
jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER

User = get_user_model()

class LoginView(generics.CreateAPIView):
	"""POST AUTH/login"""
	permission_classes = (permissions.AllowAny,)

	queryset = User.objects.all()

	def post(self, request, *args, **kwargs):
		username = request.data.get("username", "")
		password = request.data.get("password", "")
		user = authenticate(request, username=username, password=password)
		if user is not None:
			# login saves the user’s ID in the session,
			# using Django’s session framework.
			login(request, user)
			serializer = TokenSerializer(data={
				# using drf jwt utility functions to generate a token
				"token": jwt_encode_handler(
					jwt_payload_handler(user)
				)})
			serializer.is_valid()
			return Response(serializer.data)
		return Response(status=status.HTTP_401_UNAUTHORIZED)

class ListPostsView(generics.ListAPIView):
	"""
	Provides a get method handler.
	"""
	queryset = Posts.objects.all()
	serializer_class = PostsSerializer
	# permission_classes = (permissions.IsAuthenticated,)


def show_all(request):
	queryset_list = Posts.objects.all()
	if not request.user.is_authenticated:
		queryset_list = queryset_list.filter(
			   Q(is_public = True))
		context = {
			'queryset_list':queryset_list,
		}
	else:
		queryset_list = queryset_list.filter(
			   Q(user_id = request.user.id))
		context = {
				'queryset_list':queryset_list,
			}
	return render(request, 'index.html', context)



@login_required(login_url='/accounts/login/')
def create_post(request):
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit = False)
		instance.user = request.user
		instance.save()
		messages.success(request, "Post Successfully Created")
		return redirect("wrlapp:show")
	context = {
		'form' : form
	}
	return render(request,'create_post.html', context)


def retrive_post(request,id):
	queryset_list = Posts.objects.filter(id = id)
	context = {
		'queryset_list': queryset_list
	}
	return render(request,'retrive_post.html', context)


@login_required(login_url='/accounts/login/')
def update_post(request,id):
	instance = Posts.objects.filter(id = id).first()
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit = False)
		instance.save()
		messages.success(request, "Post is Updated.")
		return HttpResponseRedirect('/view/%d'%id)
	context = {
		'title' : instance.title,
		'instance' : instance,
		'form' : form
	}
	return render(request,'update_post.html', context)

@login_required(login_url='/accounts/login/')
def delete_post(request, id):
	instance = Posts.objects.get(id=id)
	instance.delete()
	messages.success(request, "Post is Deleted.")
	return redirect("wrlapp:show")


def how_it_work(request):
	context = {}
	return render(request, 'how_it_works.html', context)


def getMediumContent(request):
	form = FetchUrlContentForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit = False)
		instance.user = request.user
		instance.getUrlContent = mediumContent(form.cleaned_data['url'])
		instance.save()
		messages.success(request, "Post Successfully Created")
		return redirect("wrlapp:mediumViewContent")
	context = {
		'form' : form
	}
	return render(request,  "getMediumContent.html", context)

def retriveMediumContent(request,id):
	queryset_list = FetchUrlContent.objects.filter(id = id)
	context = {
		'queryset_list': queryset_list
	}
	return render(request,'retriveMediumContent.html', context)

def showMediumContent(request):
	queryset_list = FetchUrlContent.objects.all()
	context = {
		'queryset_list': queryset_list
	}
	return render(request, 'showMediumContent.html', context)




class MySignupView(SignupView):
	template_name = 'my_signup.html'


class MyLoginView(LoginView):
	template_name = 'my_login.html'

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <title>Create</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/internal_posts.css' %}" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  </head>
  
  <body>
    {% load socialaccount %}
    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo" style="padding-left: 20px;">TLDR</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="mobile.html">Mobile</a></li>
          {% if user.is_authenticated %}
            <li><a href="badges.html">How It Works</a></li>
            <li><a href="mobile.html">{{ user.username }}</a></li>
            <li><a href="{% url 'account_logout' %}">Log out</a></li>
          {% else %}
            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            <li><a href="badges.html">How It Works</a></li>
            <li><a href="{% url 'account_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    
    <ul class="sidenav" id="mobile-demo">
      <li><a href="sass.html">Sign UP</a></li>
      <li><a href="badges.html">How It Works </a></li>
      <li><a href="collapsible.html">Login</a></li>
      <li><a href="mobile.html">Mobile</a></li>
    </ul>
    
    {% block content %}{% endblock %}
    <script type="text/javascript" src="{% static 'js/internal_post.js' %}"></script>
  </body>
</html>

templates/base1.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
	{% if user.is_authenticated %}
	<li><a href="{% url 'account_email' %}">Change E-mail</a></li>
	<li><a href="{% url 'account_logout' %}">Sign Out</a></li>
	{% else %}
	<li><a href="{% url 'account_login' %}">Sign In</a></li>
	<li><a href="{% url 'account_signup' %}">Sign Up</a></li>
	{% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

templates/create_post.html
{% extends 'base.html' %}
{% block content %}
{% load widget_tweaks %}
<div class="container post_create">
	<h3 class="center">Create Your Post Here</h3>
    <form method="POST" action="" enctype="multipart/form-data" novalidate>
    	{% csrf_token %}
    	<div class="input-field col s12">
        {{ form.title|add_class:"input-field" }}
        <label for="id_title">Title</label>
      </div>
      <div class="input-field col s12">
        {{ form.content|add_class:"materialize-textarea" }}
        <label for="id_content">Content</label>
      </div>
      <p>
	      <label>
        	{{ form.is_public|add_class:"filled-in" }}
          <span>Is Public</span>
        </label>
	    </p>
      <input type="submit" class="btn btn-primary right" value="Create Post">
    </form>
</div>
{% endblock content %}

templates/getMediumContent.html
{% extends 'base.html' %}
{% block content %}
{% load widget_tweaks %}
<div class="container post_create">
	<h3 class="center">Create Your Post Here</h3>
    <form method="POST" action="" enctype="multipart/form-data" novalidate>
    	{% csrf_token %}
    	<div class="input-field col s12">
          {{ form.url|add_class:"input-field" }}
          <label for="id_url">URL</label>
        </div>
      <input type="submit" class="btn btn-primary right" value="Create Post">
    </form>
</div>
{% endblock content %}

templates/how_it_works.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<p>Under Construction...!!!</p>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load socialaccount %}
<div class="container row">
  <h3>Here all Posts...</h3>
    {% for query in queryset_list %}
    <div class="col s12 m12">
      <div class="card blue-grey darken-3 hoverable">
        <div class="card-content white-text">
          <span class="card-title">{{ query.title }}</span>
          <p>{{ query.content }}</p>
          <span class="card-title activator text-darken-4">
            <a href="view/{{query.id}}" class="white-text"><i class="material-icons right">arrow_forward</i></a></span>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post" 
                  action="{% url 'django.contrib.auth.views.login' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Username</label></td>
                        <td><input id="id_username" name="username" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Password</label></td>
                        <td><input id="id_password" name="password" 
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match. 
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login" 
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock content %}

templates/retriveMediumContent.html
{% extends 'base.html' %}
{% block content %}
{% load socialaccount %}
{% load markup_tags %}
<div class="container row pocket">
    {% for query in queryset_list %}
    <div class="col s12 m12">
      <div class="card white-grey darken-3 ">
         <span class="card-title activator text-darken-4">
            <a href="view/{{query.id|add:'1'}}" class="dark-text-text"><i class="material-icons right">arrow_forward</i></a></span>
             <span class="card-title activator text-darken-4">
            <a href="view/{{query.id|add:'-1'}}" class="dark-text-text"><i class="material-icons left">arrow_backward</i></a></span>
        <div class="card-content dark-text">
          <p>{{ query.getUrlContent|apply_markup:"markdown" }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/retrive_post.html
{% extends 'base.html' %}
{% block content %}
  <div class="container row">
  	{% for query in queryset_list %}
      <div class="col s12 m12 view_content">
        <h3 class="grey-text">{{ query.title }}
          <div class="fixed-action-btn horizontal"
          style="position:relative; float:right;bottom:-5px; right:10px">
          <a class="btn-floating btn-medium white">
            <i class="medium material-icons black">dehaze</i>
          </a>
          <ul>
            <li><a href="/create" class="btn-floating blue"><i class="material-icons">add</i></a></li>
            <li><a href="/{{query.id}}/update" class="btn-floating green"><i class="material-icons">edit</i></a></li>
            <li><a href="#modal1" class="btn-floating red modal-trigger"><i class="material-icons">delete</i></a></li>
          </ul>
        </div>
        </h3>
        <p>{{ query.content }}</p>
        <!-- model for delete Confirmation -->
        <div id="modal1" class="modal" style="opacity:0.1">
          <div class="modal-content">
            <h5>Are You Sure..! do you want delete this post ?</h5>
            <div class="chip">{{ query.title }}</div>
            <span>Once Delete it won't get back.</span>
          </div>
          <div class="modal-footer">
            <a href="/{{query.id}}/delete" class="modal-close waves-effect waves-green btn-flat">Agree</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>   
{% endblock content %}

templates/showMediumContent.html
{% extends 'base.html' %}
{% block content %}
{% load socialaccount %}
{% load markup_tags %}
<div class="container row pocket">  
    {% for query in queryset_list %}
    <div class="col s12 m12">
      <div class="card white-grey darken-3 ">
        <span class="card-title activator text-darken-4">
            <a href="view/{{query.id}}" class="dark-text-text"><i class="material-icons right">arrow_forward</i></a></span>
        <div class="card-content dark-text pocket-inside-content">
          <p>{{ query.getUrlContent|apply_markup:"markdown" }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/update_post.html
{% extends 'base.html' %}
{% block content %}
{% load widget_tweaks %}
<div class="container post_create">
	<h3 class="center">Update Your Post Here</h3>
    <form method="POST" action="" enctype="multipart/form-data" novalidate>
    	{% csrf_token %}
    	<div class="input-field col s12">
          {{ form.title|add_class:"input-field" }}
          <label for="id_title">Title</label>
        </div>
        <div class="input-field col s12">
          {{ form.content|add_class:"materialize-textarea" }}
          <label for="id_content">Content</label>
        </div>
        <p>
	      <label>
	      	{{ form.is_public|add_class:"filled-in" }}
	        <span>Is Public</span>
	      </label>
    	</p>
      <input type="submit" class="btn btn-primary right" value="Create Post">
    </form>
</div>
{% endblock content %}